name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Se déclenche sur un push sur la branche main

# Permissions nécessaires pour que GitHub Actions puisse publier sur Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Étape 1 : Build & Vérification
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Vérification TypeScript (pour éviter de déployer un site avec des erreurs de type)
      - name: Type Check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Étape 2 : Déploiement
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Attends que le job 'build' soit terminé avec succès
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4